# Generated by Django 4.2 on 2023-06-22 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PropertyKeyFeatures',
            new_name='PropertyKeyFeature',
        ),
    ]
