# Generated by Django 4.2 on 2023-07-13 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0001_initial'),
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listingpricebypropertycategoryhistory',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='system.currency'),
        ),
        migrations.AddField(
            model_name='listingpricebypropertycategoryhistory',
            name='property_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listing_price_by_property_category_history', to='properties.propertycategory'),
        ),
        migrations.AddField(
            model_name='listingpricebypropertycategory',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='system.currency'),
        ),
        migrations.AddField(
            model_name='listingpricebypropertycategory',
            name='property_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listing_price_by_property_category', to='properties.propertycategory'),
        ),
        migrations.AddField(
            model_name='land',
            name='land_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lands', related_query_name='land', to='properties.landtype'),
        ),
        migrations.AddField(
            model_name='land',
            name='parent_property',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='land', to='properties.property', verbose_name='main property'),
        ),
        migrations.AddField(
            model_name='condominium',
            name='parent_property',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='condominium', to='properties.property', verbose_name='main property'),
        ),
        migrations.AddField(
            model_name='commercialproperty',
            name='parent_property',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='commercial_property', to='properties.property', verbose_name='main property'),
        ),
        migrations.AddField(
            model_name='apartmentunitamenity',
            name='amenity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.amenity'),
        ),
        migrations.AddField(
            model_name='apartmentunitamenity',
            name='apartment_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.apartmentunit'),
        ),
        migrations.AddField(
            model_name='apartmentunit',
            name='apartment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apartment_units', related_query_name='apartment_unit', to='properties.apartment', verbose_name='main apartment'),
        ),
        migrations.AddField(
            model_name='apartmentunit',
            name='property_plan',
            field=models.OneToOneField(blank=True, help_text='Plan image for this unit', null=True, on_delete=django.db.models.deletion.SET_NULL, to='properties.propertyplan'),
        ),
        migrations.AddField(
            model_name='apartment',
            name='parent_property',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='apartment', to='properties.property', verbose_name='main property'),
        ),
        migrations.AddField(
            model_name='amenity',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amenities', related_query_name='amenity', to='properties.amenitycategory'),
        ),
        migrations.AddConstraint(
            model_name='propertykeyfeature',
            constraint=models.UniqueConstraint(fields=('property', 'name'), name='property_unique_feature_name_constraint'),
        ),
        migrations.AddConstraint(
            model_name='propertycategoryamenity',
            constraint=models.UniqueConstraint(fields=('property_category', 'amenity'), name='prop_cat_amenity_unique_constraint'),
        ),
        migrations.AddConstraint(
            model_name='propertyamenity',
            constraint=models.UniqueConstraint(fields=('parent_property', 'amenity'), name='property_amenity_unique_constraint'),
        ),
        migrations.AddConstraint(
            model_name='property',
            constraint=models.UniqueConstraint(condition=models.Q(('name__isnull', False)), fields=('name', 'agent'), name='unique_property_name_in_an_agent_constraint', violation_error_message='A property should have a unique name within the property. [name, agent] duplicate.'),
        ),
        migrations.AddConstraint(
            model_name='othercommercialpropertyunitamenity',
            constraint=models.UniqueConstraint(fields=('other_commercial_property_unit', 'amenity'), name='other_commercial_property_unit_amenity_constraint'),
        ),
        migrations.AddConstraint(
            model_name='othercommercialpropertyunit',
            constraint=models.UniqueConstraint(fields=('commercial_property', 'unit_name_or_number'), name='unique_other_unit_in_single_commercial_property_constraint'),
        ),
        migrations.AddConstraint(
            model_name='officeunitamenity',
            constraint=models.UniqueConstraint(fields=('office_unit', 'amenity'), name='office_unit_amenity_constraint'),
        ),
        migrations.AddConstraint(
            model_name='officeunit',
            constraint=models.UniqueConstraint(fields=('commercial_property', 'unit_name_or_number'), name='unique_office_unit_in_single_commercial_property_constraint'),
        ),
        migrations.AddConstraint(
            model_name='listingpricebypropertycategoryhistory',
            constraint=models.UniqueConstraint(fields=('property_category', 'listing_type'), name='single_listing_price_by_property_category_history_constraint'),
        ),
        migrations.AddConstraint(
            model_name='apartmentunitamenity',
            constraint=models.UniqueConstraint(fields=('apartment_unit', 'amenity'), name='apartment_unit_amenity_unique_constraint'),
        ),
        migrations.AddConstraint(
            model_name='amenity',
            constraint=models.UniqueConstraint(fields=('id', 'category'), name='unique-amenity-category-constriant'),
        ),
    ]
