# Generated by Django 4.2 on 2023-07-28 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commercialproperty',
            name='unit_type',
            field=models.CharField(choices=[('OTHER_UNIT', 'Other unit'), ('OFFICE_UNIT', 'Office unit')], default='OFFICE_UNIT', max_length=20, verbose_name='commercial property unit type'),
            preserve_default=False,
        ),
    ]
