# Generated by Django 4.2 on 2023-06-28 06:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0010_rename_agentdiscount_agentdiscounttracker'),
        ('properties', '0003_remove_listingpricebypropertycategory_single_listing_price_by_property_category_constraint_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='agent',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='agent_properties', related_query_name='agent_property', to='agents.agent', verbose_name='property agent'),
            preserve_default=False,
        ),
    ]
