# Generated by Django 4.2 on 2023-08-08 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_alter_amenity_description_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='listingpricebypropertycategoryhistory',
            name='single_listing_price_by_property_category_history_constraint',
        ),
        migrations.RemoveField(
            model_name='listingpricebypropertycategory',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='listingpricebypropertycategory',
            name='expire_on',
        ),
        migrations.RemoveField(
            model_name='listingpricebypropertycategoryhistory',
            name='expire_on',
        ),
        migrations.AddConstraint(
            model_name='listingpricebypropertycategory',
            constraint=models.UniqueConstraint(fields=('property_category', 'listing_type'), name='single_listing_price_by_property_category_constraint'),
        ),
    ]
