# Generated by Django 4.2 on 2023-06-28 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_property_agent'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='property',
            constraint=models.UniqueConstraint(fields=('name', 'agent'), name='unique_property_name_in_an_agent_constraint'),
        ),
    ]
