# Generated by Django 4.2 on 2023-08-10 17:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "properties",
            "0005_remove_listingpricebypropertycategoryhistory_single_listing_price_by_property_category_history_const",
        ),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="listingpricebypropertycategory",
            name="single_listing_price_by_property_category_constraint",
        ),
        migrations.AlterField(
            model_name="listingpricebypropertycategory",
            name="listing_type",
            field=models.CharField(
                choices=[("RENT", "RENT"), ("SALE", "SALE")], max_length=20
            ),
        ),
        migrations.AddConstraint(
            model_name="listingpricebypropertycategory",
            constraint=models.UniqueConstraint(
                fields=("property_category", "listing_type"),
                name="single_listing_price_by_property_category_constraint",
            ),
        ),
    ]
