# Generated by Django 4.2 on 2023-06-28 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0005_property_unique_property_name_in_an_agent_constraint'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='property',
            name='unique_property_name_in_an_agent_constraint',
        ),
        migrations.AddConstraint(
            model_name='property',
            constraint=models.UniqueConstraint(condition=models.Q(('name__isnull', False)), fields=('name', 'agent'), name='unique_property_name_in_an_agent_constraint', violation_error_message='A property should have a unique name within the property. [name, agent] duplicate.'),
        ),
    ]
