# Generated by Django 4.2 on 2023-06-28 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0006_remove_property_unique_property_name_in_an_agent_constraint_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sharehouse',
            old_name='is_furnished',
            new_name='shared_rooms_furnished',
        ),
    ]
