# Generated by Django 4.2 on 2023-06-28 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0007_rename_is_furnished_sharehouse_shared_rooms_furnished'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apartment',
            name='is_multi_unit',
        ),
        migrations.RemoveField(
            model_name='commercialproperty',
            name='is_multi_unit',
        ),
    ]
