# Generated by Django 4.2 on 2023-08-26 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0007_remove_commercialproperty_unit_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buildingtype',
            name='type',
            field=models.CharField(choices=[('APARTMENT', 'APARTMENT'), ('CONDOMINIUM', 'CONDOMINIUM'), ('TOWNHOUSE', 'TOWNHOUSE'), ('VILLA', 'VILLA'), ('OTHER', 'OTHER')], max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='commercialproperty',
            name='status',
            field=models.CharField(choices=[('NEW', 'NEW'), ('RESTORED', 'RESTORED'), ('IN_GOOD_CONDITION', 'IN_GOOD_CONDITION'), ('OLD', 'OLD')], max_length=50, verbose_name='current status of the property'),
        ),
        migrations.AlterField(
            model_name='condominium',
            name='status',
            field=models.CharField(choices=[('NEW', 'NEW'), ('RESTORED', 'RESTORED'), ('IN_GOOD_CONDITION', 'IN_GOOD_CONDITION'), ('OLD', 'OLD')], max_length=50, verbose_name='current status of the property'),
        ),
        migrations.AlterField(
            model_name='property',
            name='tax_band',
            field=models.CharField(choices=[('BAND_A', 'BAND_A'), ('BBND_B', 'BBND_B'), ('BAND_C', 'BAND_C')], max_length=50),
        ),
        migrations.AlterField(
            model_name='property',
            name='tenure',
            field=models.CharField(choices=[('FREEHOLD', 'FREEHOLD'), ('LEASEHOLD', 'LEASEHOLD'), ('COMMONHOLD', 'COMMONHOLD')], max_length=100),
        ),
        migrations.AlterField(
            model_name='room',
            name='for_gender',
            field=models.CharField(choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE'), ('ANY', 'ANY')], max_length=30, verbose_name='required of gender of new flatmate'),
        ),
        migrations.AlterField(
            model_name='sharehouse',
            name='status',
            field=models.CharField(choices=[('NEW', 'NEW'), ('RESTORED', 'RESTORED'), ('IN_GOOD_CONDITION', 'IN_GOOD_CONDITION'), ('OLD', 'OLD')], max_length=50, verbose_name='current status of the property'),
        ),
        migrations.AlterField(
            model_name='sharehouse',
            name='structure',
            field=models.CharField(choices=[('DETACHED', 'DETACHED'), ('SEMI_DETACHED', 'SEMI_DETACHED'), ('TERRACED', 'TERRACED'), ('IN_COMPOUND', 'IN_COMPOUND')], max_length=100, verbose_name='property structure'),
        ),
        migrations.AlterField(
            model_name='townhouse',
            name='status',
            field=models.CharField(choices=[('NEW', 'NEW'), ('RESTORED', 'RESTORED'), ('IN_GOOD_CONDITION', 'IN_GOOD_CONDITION'), ('OLD', 'OLD')], max_length=50, verbose_name='current status of the property'),
        ),
        migrations.AlterField(
            model_name='townhouse',
            name='structure',
            field=models.CharField(choices=[('DETACHED', 'DETACHED'), ('SEMI_DETACHED', 'SEMI_DETACHED'), ('TERRACED', 'TERRACED'), ('IN_COMPOUND', 'IN_COMPOUND')], max_length=100, verbose_name='property structure'),
        ),
        migrations.AlterField(
            model_name='villa',
            name='status',
            field=models.CharField(choices=[('NEW', 'NEW'), ('RESTORED', 'RESTORED'), ('IN_GOOD_CONDITION', 'IN_GOOD_CONDITION'), ('OLD', 'OLD')], max_length=50, verbose_name='current status of the property'),
        ),
    ]
