# Generated by Django 4.2 on 2023-06-28 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0008_remove_apartment_is_multi_unit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commercialproperty',
            name='area',
        ),
        migrations.RemoveField(
            model_name='commercialproperty',
            name='bath_rooms',
        ),
        migrations.RemoveField(
            model_name='commercialproperty',
            name='bed_rooms',
        ),
        migrations.RemoveField(
            model_name='commercialproperty',
            name='floor',
        ),
        migrations.RemoveField(
            model_name='commercialproperty',
            name='is_furnished',
        ),
    ]
