# Generated by Django 4.2 on 2023-06-28 18:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0009_remove_commercialproperty_area_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='villa',
            name='floor',
        ),
        migrations.AddField(
            model_name='villa',
            name='floors',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0)], verbose_name='number of fields'),
        ),
    ]
