# Generated by Django 4.2 on 2023-07-06 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0011_land_land_type'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='apartmentunitamenity',
            constraint=models.UniqueConstraint(fields=('apartment_unit', 'amenity'), name='apartment_unit_amenity_unique_constraint'),
        ),
    ]
