# Generated by Django 4.2 on 2023-07-06 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0012_apartmentunitamenity_apartment_unit_amenity_unique_constraint'),
    ]

    operations = [
        migrations.RenameField(
            model_name='officeunitamenity',
            old_name='other_commercial_property_unit',
            new_name='office_unit',
        ),
        migrations.AddConstraint(
            model_name='officeunitamenity',
            constraint=models.UniqueConstraint(fields=('office_unit', 'amenity'), name='office_unit_amenity_constraint'),
        ),
        migrations.AddConstraint(
            model_name='othercommercialpropertyunitamenity',
            constraint=models.UniqueConstraint(fields=('other_commercial_property_unit', 'amenity'), name='other_commercial_property_unit_amenity_constraint'),
        ),
    ]
