# Generated by Django 4.2 on 2023-05-19 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='system',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='system module name'),
        ),
    ]
