# Generated by Django 4.2 on 2023-07-27 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmethod',
            name='approval_mode',
            field=models.CharField(choices=[('AUTO', 'Automatic'), ('MANUAL', 'Manual')], default=1, max_length=30, verbose_name='payment approval mode'),
            preserve_default=False,
        ),
    ]
