# Generated by Django 4.2 on 2023-05-19 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0002_alter_system_name'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='discount',
            name='discount_constraint',
        ),
        migrations.AlterField(
            model_name='discount',
            name='name',
            field=models.CharField(max_length=200, unique=True, verbose_name='discount name'),
        ),
        migrations.AddConstraint(
            model_name='discount',
            constraint=models.CheckConstraint(check=models.Q(('action__exact', 'COUNT'), ('unit__exact', 'SUBSCRIPTION')), name='discount_constraint', violation_error_message='Incompatible action unit for this discount!'),
        ),
    ]
