# Generated by Django 4.2 on 2023-07-28 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0003_paymentmethod_approval_mode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listingparameter',
            name='will_expire_after_days',
        ),
        migrations.AlterField(
            model_name='listingparameter',
            name='name',
            field=models.CharField(choices=[('*', '*'), ('AGENT_REFERRAL_COUPON', 'Agent Referral Coupon'), ('LISTING_LIFE_TIME', 'Listing life time')], max_length=200, unique=True, verbose_name='parameter name'),
        ),
    ]
