# Generated by Django 4.2 on 2023-05-19 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0003_remove_discount_discount_constraint_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='discount',
            name='discount_constraint',
        ),
    ]
