# Generated by Django 4.2 on 2023-05-19 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0004_remove_discount_discount_constraint'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='deadline',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='discount',
            name='action',
            field=models.CharField(choices=[('COUNT', 'Count'), ('SINGLE', 'Single'), ('DEADLINE', 'Deadline')], help_text='determines how the system calculated length of discount period                                 or amount. It can have count, single, or deadline', max_length=50, verbose_name='Discount Action Type'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='discount_type',
            field=models.CharField(choices=[('PAY_PER_LISTING', 'Pay-per-listing'), ('SUBSCRIPTION', 'Subscription')], max_length=50),
        ),
        migrations.AlterField(
            model_name='discount',
            name='unit',
            field=models.CharField(choices=[('DAYS', 'Days'), ('LISTINGS', 'Listings'), ('SUBSCRIPTION', 'Subscription')], help_text='It can be days, listings or subscription', max_length=50, verbose_name='discount value unit'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='value',
            field=models.IntegerField(blank=True, default=1, help_text='Unit value. i.e. 5 days, or 10 listings, etc'),
        ),
        migrations.AlterField(
            model_name='servicesubscriptionplan',
            name='billing_cycle',
            field=models.CharField(choices=[('DAY', 'Day'), ('WEEK', 'Week'), ('MONTH', 'Month'), ('YEAR', 'Year')], max_length=20, verbose_name='unit of billing period'),
        ),
        migrations.AlterField(
            model_name='servicesubscriptionplan',
            name='period_unit',
            field=models.CharField(choices=[('DAY', 'Day'), ('WEEK', 'Week'), ('MONTH', 'Month'), ('YEAR', 'Year')], max_length=20, verbose_name='unit of period'),
        ),
    ]
