# Generated by Django 4.2 on 2023-07-29 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0004_remove_listingparameter_will_expire_after_days_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmethod',
            name='name',
            field=models.CharField(choices=[('CARD', 'Card'), ('VOUCHER', 'Voucher'), ('MOBILE_PAYMENT', 'Mobile Payment'), ('BANK_TRANSFER', 'Bank Transfer')], max_length=100, unique=True, verbose_name='payment method name'),
        ),
    ]
