# Generated by Django 4.2 on 2023-07-30 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0005_alter_paymentmethod_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listingparameter',
            name='name',
            field=models.CharField(choices=[('*', '*'), ('AGENT_REFERRAL_COUPON', 'AGENT_REFERRAL_COUPON'), ('LISTING_LIFE_TIME', 'LISTING_LIFE_TIME')], max_length=200, unique=True, verbose_name='parameter name'),
        ),
        migrations.AlterField(
            model_name='systemparameter',
            name='name',
            field=models.CharField(choices=[('*', '*'), ('VOUCHER_LIFE_TIME', 'VOUCHER_LIFE_TIME'), ('COUPON_LIFE_TIME', 'COUPON_LIFE_TIME')], max_length=200, unique=True, verbose_name='parameter name'),
        ),
    ]
