# Generated by Django 4.2 on 2023-05-19 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0005_discount_deadline_alter_discount_action_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
