# Generated by Django 4.2 on 2023-07-30 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0006_alter_listingparameter_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationtopic',
            name='name',
            field=models.CharField(choices=[('NEW_PROPERTY_ADDED', 'New Property Addded'), ('NEW_LISTING_ADDED', 'New Listing Addded'), ('PAYMENT_REQUESTED', 'Payment Requested'), ('PAYMENT_APPROVED', 'Payment Approved'), ('MARKETING', 'Marketing'), ('LISTING_VIEWED', 'Listing Viewed')], max_length=200, verbose_name='topic name'),
        ),
        migrations.AlterField(
            model_name='notificationtopic',
            name='target_group',
            field=models.CharField(choices=[('USER', 'User'), ('AGENT', 'Agent')], help_text='The target user group that this notifications to be sent                                         to with is topic', max_length=30),
        ),
    ]
