# Generated by Django 4.2 on 2023-05-20 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0006_alter_discount_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicesubscriptionplan',
            name='base_number_of_branchs',
            field=models.PositiveIntegerField(default=1, help_text='Maximum number of branchs with the base price.                                                                     If more than this number, then addtional fees apply.', verbose_name='Base number of branchs'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='action',
            field=models.CharField(choices=[('COUNT', 'Count'), ('SINGLE', 'Single'), ('DEADLINE', 'Deadline')], help_text='determines how the system calculated length of discount period                                 or amount. It can have count, single, or deadline.', max_length=50, verbose_name='Discount Action Type'),
        ),
    ]
