# Generated by Django 4.2 on 2023-07-30 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0007_alter_notificationtopic_name_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='notificationtopic',
            name='notification_topic_unique_together_constraint',
        ),
        migrations.AddConstraint(
            model_name='notificationtopic',
            constraint=models.UniqueConstraint(fields=('id', 'name'), name='notification_topic_unique_together_constraint'),
        ),
    ]
