# Generated by Django 4.2 on 2023-07-30 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0008_remove_notificationtopic_notification_topic_unique_together_constraint_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='notificationtopic',
            name='notification_topic_unique_together_constraint',
        ),
        migrations.AlterField(
            model_name='notificationtopic',
            name='name',
            field=models.CharField(choices=[('NEW_PROPERTY_ADDED', 'New Property Addded'), ('NEW_LISTING_ADDED', 'New Listing Addded'), ('PAYMENT_ORDER_REQUESTED', 'Payment Order Requested'), ('PAYMENT_OREDR_APPROVED', 'Payment Order Approved'), ('MARKETING', 'Marketing'), ('LISTING_VIEWED', 'Listing Viewed')], max_length=200, verbose_name='topic name'),
        ),
        migrations.AddConstraint(
            model_name='notificationtopic',
            constraint=models.UniqueConstraint(fields=('target_group', 'name'), name='notification_topic_unique_together_constraint'),
        ),
    ]
