# Generated by Django 4.2 on 2023-05-20 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0009_alter_systemrating_rating'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='systemrating',
            constraint=models.UniqueConstraint(fields=('user', 'system'), name='user_can_rate_once_constraint', violation_error_message='A user can only rate a system once.                                         Consider editing your rating instead!'),
        ),
    ]
