# Generated by Django 4.2 on 2023-08-04 22:44

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0010_alter_discount_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Periodicity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('name', models.CharField(choices=[('DAY', 'DAY'), ('WEEK', 'WEEK'), ('MONTH', 'MONTH'), ('YEAR', 'YEAR')], max_length=30, unique=True, verbose_name='periodicity name')),
                ('lenth', models.PositiveIntegerField(verbose_name='period length')),
                ('length_unit', models.CharField(choices=[('SECOND', 'SECOND'), ('MINUTE', 'MINUTE'), ('HOUR', 'HOUR'), ('DAY', 'DAY')], max_length=30, verbose_name='period length unit')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RenameField(
            model_name='servicesubscriptionplan',
            old_name='base_price',
            new_name='subscription_price',
        ),
        migrations.RemoveField(
            model_name='servicesubscriptionplan',
            name='base_currency',
        ),
        migrations.RemoveField(
            model_name='servicesubscriptionplan',
            name='base_number_of_branchs',
        ),
        migrations.RemoveField(
            model_name='servicesubscriptionplan',
            name='billing_cycle_length',
        ),
        migrations.RemoveField(
            model_name='servicesubscriptionplan',
            name='listing_parameter',
        ),
        migrations.RemoveField(
            model_name='servicesubscriptionplan',
            name='period_length',
        ),
        migrations.RemoveField(
            model_name='servicesubscriptionplan',
            name='period_unit',
        ),
        migrations.RemoveField(
            model_name='servicesubscriptionplan',
            name='price_increase_by_branch_fixed',
        ),
        migrations.RemoveField(
            model_name='servicesubscriptionplan',
            name='price_increase_by_branch_percentage',
        ),
        migrations.AddField(
            model_name='servicesubscriptionplan',
            name='base_number_of_branches',
            field=models.PositiveIntegerField(default=1, help_text='Maximum number of branchs with the base price. If more than this number, then addtional fees apply.', verbose_name='Base number of branchs'),
        ),
        migrations.AddField(
            model_name='servicesubscriptionplan',
            name='price_increase_by_branch_fixed_value',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='The fixed rate that the subscription plan price is increased as the number of branches encrease', max_digits=12),
        ),
        migrations.AddField(
            model_name='servicesubscriptionplan',
            name='price_increase_by_branch_percentage_value',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='The percentage of the base price that the subscription plan price is increased as the number of branches encrease', max_digits=12),
        ),
        migrations.AlterField(
            model_name='notificationtopic',
            name='name',
            field=models.CharField(choices=[('NEW_PROPERTY_ADDED', 'New Property Addded'), ('NEW_LISTING_ADDED', 'New Listing Addded'), ('PAYMENT_ORDER_REQUESTED', 'Payment Order Requested'), ('PAYMENT_ORDER_APPROVED', 'Payment Order Approved'), ('MARKETING', 'Marketing'), ('LISTING_VIEWED', 'Listing Viewed'), ('NEW_AGENT_ADDED', 'New Agent Added'), ('NEW_AGENT_BRANCH_ADDED', 'New Agent Branch Added')], max_length=200, verbose_name='topic name'),
        ),
        migrations.AddField(
            model_name='servicesubscriptionplan',
            name='subscription_period',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='subscription_period', to='system.periodicity'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='servicesubscriptionplan',
            name='billing_cycle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_billing_cycle', to='system.periodicity'),
        ),
    ]
