# Generated by Django 4.2 on 2023-05-20 13:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('system', '0010_systemrating_user_can_rate_once_constraint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemfeedback',
            name='user',
            field=models.ForeignKey(blank=True, default=None, help_text='User id will be set to -1 by default if user is anonymous', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='system_feedbacks', related_query_name='system_feedback', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='systemrating',
            name='user',
            field=models.ForeignKey(blank=True, default=None, help_text='User id will be set to -1 by default if user is anonymous', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='system_ratings', related_query_name='system_rating', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='systemfeedback',
            constraint=models.UniqueConstraint(fields=('user', 'system'), name='user_can_give_feedback_once_constraint', violation_error_message='A user can give feedback only once.                                         Consider editing your feedback instead!'),
        ),
    ]
