# Generated by Django 4.2 on 2023-08-04 22:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0011_periodicity_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='periodicity',
            options={'verbose_name_plural': 'Periodicities'},
        ),
        migrations.AddField(
            model_name='periodicity',
            name='system',
            field=models.ForeignKey(default=1, help_text='The system module that the periodicity applies to', on_delete=django.db.models.deletion.CASCADE, related_name='periodicities', related_query_name='periodicity', to='system.system', verbose_name='system module'),
            preserve_default=False,
        ),
    ]
