# Generated by Django 4.2 on 2023-05-20 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0011_alter_systemfeedback_user_alter_systemrating_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='redeemed_on',
        ),
    ]
