# Generated by Django 4.2 on 2023-05-20 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0012_remove_coupon_redeemed_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='featuringprice',
            name='system',
            field=models.ForeignKey(default=1, help_text='The system module that this featuring price applies to', on_delete=django.db.models.deletion.CASCADE, related_name='featuring_prices', related_query_name='featuring_price', to='system.system', verbose_name='System Module'),
            preserve_default=False,
        ),
    ]
