# Generated by Django 4.2 on 2023-08-04 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0012_alter_periodicity_options_periodicity_system'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicesubscriptionplan',
            name='billing_cycle_length',
            field=models.PositiveIntegerField(default=1, verbose_name='length of billing cycle period'),
        ),
        migrations.AddField(
            model_name='servicesubscriptionplan',
            name='subscription_period_length',
            field=models.PositiveIntegerField(default=1, verbose_name='length of subscription period'),
        ),
        migrations.AlterField(
            model_name='servicesubscriptionplan',
            name='name',
            field=models.CharField(choices=[('AGENT_MONTHLY_BILLED_MONTHLY', 'AGENT_MONTHLY_BILLED_MONTHLY'), ('AGENT_MONTHLY_BILLED_MONTHLY', 'AGENT_MONTHLY_BILLED_QUARTERLY'), ('AGENT_MONTHLY_BILLED_SEMI_ANUALLY', 'AGENT_MONTHLY_BILLED_SEMI_ANUALLY'), ('AGENT_MONTHLY_BILLED_YEARLY', 'AGENT_MONTHLY_BILLED_YEARLY')], max_length=200, verbose_name='service subscription plan name'),
        ),
        migrations.AlterField(
            model_name='servicesubscriptionplan',
            name='subscription_price',
            field=models.DecimalField(decimal_places=5, max_digits=12, verbose_name='subscription price'),
        ),
    ]
