# Generated by Django 4.2 on 2023-08-05 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0013_servicesubscriptionplan_billing_cycle_length_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='periodicity',
            old_name='lenth',
            new_name='length',
        ),
        migrations.AlterField(
            model_name='notificationtopic',
            name='name',
            field=models.CharField(choices=[('NEW_AGENT_ADDED', 'NEW_AGENT_ADDED'), ('NEW_AGENT_BRANCH_ADDED', 'NEW_AGENT_BRANCH_ADDED'), ('NEW_PROPERTY_ADDED', 'NEW_PROPERTY_ADDED'), ('NEW_LISTING_ADDED', 'NEW_LISTING_ADDED'), ('PAYMENT_ORDER_REQUESTED', 'PAYMENT_ORDER_REQUESTED'), ('PAYMENT_ORDER_APPROVED', 'PAYMENT_ORDER_APPROVED'), ('NEW_AGENT_SERVICE_SUBSCRIPTION', 'NEW_AGENT_SERVICE_SUBSCRIPTION'), ('MARKETING', 'MARKETING'), ('LISTING_VIEWED', 'LISTING_VIEWED')], max_length=200, verbose_name='topic name'),
        ),
    ]
