# Generated by Django 4.2 on 2023-05-20 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0013_featuringprice_system'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='iso_4217_num_code',
            field=models.CharField(default='230', max_length=3, unique=True, verbose_name='numeric code of the currency'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='use_count',
            field=models.PositiveIntegerField(default=0, help_text='How many times redeemed so far', verbose_name='use counts'),
        ),
        migrations.AlterField(
            model_name='currency',
            name='iso_4217_alpha_code',
            field=models.CharField(default='ETB', max_length=3, unique=True, verbose_name='alphabetic code of the currency'),
        ),
    ]
