# Generated by Django 4.2 on 2023-05-27 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0014_currency_iso_4217_num_code_alter_coupon_use_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='exchange_rate',
            field=models.DecimalField(blank=True, decimal_places=5, default=0.0, max_digits=10),
        ),
    ]
