# Generated by Django 4.2 on 2023-08-08 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0014_rename_lenth_periodicity_length_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discount',
            name='deadline',
        ),
        migrations.RemoveField(
            model_name='discount',
            name='discount_type',
        ),
        migrations.RemoveField(
            model_name='discount',
            name='listing_parameter',
        ),
        migrations.AddField(
            model_name='discount',
            name='payment_type',
            field=models.CharField(choices=[('SUBSCRIPTION', 'SUBSCRIPTION'), ('PAY_PER_LISTING', 'PAY_PER_LISTING')], default='SUBSCRIPTION', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='discount',
            name='action',
            field=models.CharField(choices=[('COUNT', 'COUNT'), ('SINGLE', 'SINGLE'), ('COUNT', 'COUNT')], help_text='determines how the system calculated length of discount period                     or amount. It can have count, single, or deadline.', max_length=50, verbose_name='Discount Action Type'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='name',
            field=models.CharField(choices=[('PROMOTIONAL_DISCOUNT', 'PROMOTIONAL_DISCOUNT'), ('NEW_AGENT_DISCOUNT', 'NEW_AGENT_DISCOUNT'), ('SUBSCRIPTION_RENEWAL_DISCOUNT', 'SUBSCRIPTION_RENEWAL_DISCOUNT'), ('SEASONAL_DISCOUNT', 'SEASONAL_DISCOUNT'), ('LOYALTY_DISCOUNT', 'LOYALTY_DISCOUNT')], max_length=200, verbose_name='discount name'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='unit',
            field=models.CharField(choices=[('DAY', 'DAY'), ('LISTING', 'LISTING'), ('SUBSCRIPTION', 'SUBSCRIPTION')], help_text='It can be days, listings or subscription', max_length=50, verbose_name='discount value unit'),
        ),
    ]
