# Generated by Django 4.2 on 2023-06-09 21:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0015_alter_currency_exchange_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='referralrewardplan',
            name='reward_active_time_in_days',
        ),
        migrations.AddField(
            model_name='referralrewardplan',
            name='start_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='listingparameter',
            name='name',
            field=models.CharField(max_length=200, unique=True, verbose_name='parameter name'),
        ),
        migrations.AlterField(
            model_name='system',
            name='name',
            field=models.CharField(choices=[('*', '*'), ('MYPROPERTY', 'Property renting/selling system')], max_length=100, unique=True, verbose_name='system module name'),
        ),
    ]
