# Generated by Django 4.2 on 2023-08-08 21:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0015_remove_discount_deadline_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='expire_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='discount',
            name='action',
            field=models.CharField(choices=[('COUNT', 'COUNT'), ('SINGLE', 'SINGLE'), ('DEADLINE', 'DEADLINE')], help_text='determines how the system calculated length of discount period                     or amount. It can have count, single, or deadline.', max_length=50, verbose_name='Discount Action Type'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='name',
            field=models.CharField(choices=[('NEW_AGENT_DISCOUNT', 'NEW_AGENT_DISCOUNT'), ('SUBSCRIPTION_RENEWAL_DISCOUNT', 'SUBSCRIPTION_RENEWAL_DISCOUNT'), ('SEASONAL_DISCOUNT', 'SEASONAL_DISCOUNT'), ('LOYALTY_DISCOUNT', 'LOYALTY_DISCOUNT')], max_length=200, verbose_name='discount name'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='unit',
            field=models.CharField(choices=[('DAY', 'DAY'), ('LISTING', 'LISTING'), ('NONE', 'NONE')], help_text='It can be days, listings or subscription', max_length=50, verbose_name='discount value unit'),
        ),
        migrations.AlterField(
            model_name='listingparameter',
            name='name',
            field=models.CharField(choices=[('*', '*'), ('AGENT_REFERRAL_COUPON', 'AGENT_REFERRAL_COUPON'), ('LISTING_LIFE_TIME', 'LISTING_LIFE_TIME'), ('NEW_AGENT_PERIOD', 'NEW_AGENT_PERIOD')], max_length=200, unique=True, verbose_name='parameter name'),
        ),
        migrations.AlterField(
            model_name='system',
            name='name',
            field=models.CharField(choices=[('*', '*'), ('MYPROPERTY', 'MYPROPERTY')], max_length=100, unique=True, verbose_name='system module name'),
        ),
    ]
