# Generated by Django 4.2 on 2023-06-09 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0016_remove_referralrewardplan_reward_active_time_in_days_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referralrewardplan',
            name='name',
            field=models.CharField(max_length=200, unique=True, verbose_name='reward plan name'),
        ),
        migrations.AlterField(
            model_name='referralrewardplan',
            name='number_of_referrals_needed',
            field=models.PositiveIntegerField(blank=True, default=1, help_text='Number of referral actions needed to get the reward.'),
        ),
    ]
