# Generated by Django 4.2 on 2023-08-10 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0017_discount_start_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listingparameter',
            name='name',
            field=models.CharField(choices=[('*', '*'), ('AGENT_REFERRAL_COUPON', 'AGENT_REFERRAL_COUPON'), ('LISTING_LIFE_TIME', 'LISTING_LIFE_TIME'), ('NEW_AGENT_GRACE_PERIOD', 'NEW_AGENT_GRACE_PERIOD'), ('LOYALTY_DISCOUNT_PRESUBSCRIPTIONS', 'LOYALTY_DISCOUNT_PRESUBSCRIPTIONS'), ('RESUBSCRIPTION_GRACE_PERIOD', 'RESUBSCRIPTION_GRACE_PERIOD'), ('DISCOUNT_TRACKER_LIFETIME', 'DISCOUNT_TRACKER_LIFETIME')], max_length=200, unique=True, verbose_name='parameter name'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='name',
            field=models.CharField(choices=[('CARD', 'CARD'), ('VOUCHER', 'VOUCHER'), ('MOBILE_PAYMENT', 'MOBILE_PAYMENT'), ('BANK_TRANSFER', 'BANK_TRANSFER')], max_length=100, unique=True, verbose_name='payment method name'),
        ),
    ]
