# Generated by Django 4.2 on 2023-06-10 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0017_alter_referralrewardplan_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listingparameter',
            name='will_expire_after_days',
            field=models.PositiveIntegerField(default=1, verbose_name='How many days will conf stay valid'),
        ),
        migrations.AlterField(
            model_name='listingparameter',
            name='name',
            field=models.CharField(choices=[('*', '*'), ('AGENT_REFERRAL_COUPON', 'Agent Referral Coupon')], max_length=200, unique=True, verbose_name='parameter name'),
        ),
    ]
