# Generated by Django 4.2 on 2023-06-11 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0018_listingparameter_will_expire_after_days_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='referralrewardplan',
            old_name='reward_fixed_value',
            new_name='referee_reward_fixed_value',
        ),
        migrations.RenameField(
            model_name='referralrewardplan',
            old_name='reward_percentage_value',
            new_name='referee_reward_percentage_value',
        ),
        migrations.AddField(
            model_name='referralrewardplan',
            name='referrer_reward_fixed_value',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='referralrewardplan',
            name='referrer_reward_percentage_value',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
