# Generated by Django 4.2 on 2023-07-26 15:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='approved_on',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
