# Generated by Django 4.2 on 2023-07-29 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_rename_amount_banktransfer_paid_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='ordered_on',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='transaction_reference_number',
        ),
        migrations.AddField(
            model_name='banktransfer',
            name='transaction_reference_number',
            field=models.CharField(default='ddd', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cardpayment',
            name='transaction_reference_number',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mobilepayment',
            name='transaction_reference_number',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='voucherpayment',
            name='transaction_reference_number',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='payment',
            name='approved_on',
            field=models.DateField(null=True),
        ),
    ]
