# Generated by Django 4.2 on 2023-07-29 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_remove_payment_ordered_on_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='exchange_rate',
            field=models.DecimalField(decimal_places=5, default=1.0, max_digits=10, max_length=10),
        ),
    ]
