# Generated by Django 4.2 on 2023-07-30 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_alter_payment_exchange_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_purpose',
            field=models.CharField(choices=[('LISTING', 'LISTING'), ('FEATURING', 'FEATURING'), ('SUBSCRIPTION', 'SUBSCRIPTION')], max_length=250),
        ),
    ]
