# Generated by Django 4.2 on 2023-07-31 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_alter_payment_payment_purpose'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_purpose',
            field=models.CharField(choices=[('LISTING', 'LISTING'), ('FEATURING', 'FEATURING'), ('VOUCHER_PURCHASE', 'VOUCHER_PURCHASE')], max_length=250),
        ),
    ]
