# Generated by Django 4.2 on 2023-07-31 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0007_alter_payment_payment_purpose'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='order_no',
            field=models.CharField(max_length=20, verbose_name='order number'),
        ),
    ]
