# Generated by Django 4.2 on 2023-08-05 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0008_alter_payment_order_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_purpose',
            field=models.CharField(choices=[('LISTING', 'LISTING'), ('FEATURING', 'FEATURING'), ('SUBSCRIPTION', 'SUBSCRIPTION'), ('VOUCHER_PURCHASE', 'VOUCHER_PURCHASE')], max_length=250),
        ),
    ]
