# Generated by Django 4.2 on 2023-05-10 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_is_admin_mypropertyuser_is_superuser_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mypropertyuser',
            name='group',
        ),
    ]
