# Generated by Django 4.2 on 2023-05-10 21:23

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0004_remove_mypropertyuser_group'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mypropertyuser',
            options={'verbose_name': 'User'},
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Role Name')),
                ('description', models.TextField()),
                ('added_on', models.DateField(default=django.utils.timezone.now)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_set', related_query_name='roles', to='auth.group', verbose_name='User group this role belongs  to')),
                ('permissions', models.ManyToManyField(help_text='Permissions specific to this user!', related_name='role_set', related_query_name='roles', to='auth.permission')),
            ],
        ),
        migrations.AddField(
            model_name='mypropertyuser',
            name='roles',
            field=models.ManyToManyField(related_name='user_set', related_query_name='users', to='users.role', verbose_name='User Roles'),
        ),
    ]
