# Generated by Django 4.2 on 2023-05-11 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0006_alter_role_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mypropertyuser',
            name='roles',
            field=models.ManyToManyField(related_name='user_set', related_query_name='user', to='users.role', verbose_name='User Roles'),
        ),
        migrations.AlterField(
            model_name='role',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_set', related_query_name='role', to='auth.group', verbose_name='User group this role belongs  to'),
        ),
        migrations.AlterField(
            model_name='role',
            name='permissions',
            field=models.ManyToManyField(help_text='Permissions specific to this user!', related_name='role_set', related_query_name='role', to='auth.permission'),
        ),
    ]
