# Generated by Django 4.2 on 2023-05-11 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_mypropertyuser_roles_alter_role_group_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mypropertyuser',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status'),
        ),
    ]
