# Generated by Django 4.2 on 2023-05-15 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_remove_mypropertyuser_is_blocked_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mypropertyuser',
            options={'ordering': ['-registered_on'], 'verbose_name': 'User'},
        ),
    ]
