# Generated by Django 4.2 on 2023-07-27 22:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_initial'),
        ('payments', '0002_payment_approved_on'),
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commercialpropertylisting',
            name='commercial_property',
        ),
        migrations.RemoveField(
            model_name='commercialpropertylisting',
            name='listing',
        ),
        migrations.RemoveField(
            model_name='sharehouselisting',
            name='listing',
        ),
        migrations.RemoveField(
            model_name='sharehouselisting',
            name='sharehouse',
        ),
        migrations.RemoveField(
            model_name='apartmentunitlisting',
            name='apartment_listing',
        ),
        migrations.RemoveField(
            model_name='officelisting',
            name='commercial_property_listing',
        ),
        migrations.RemoveField(
            model_name='othercommercialpropertyunitlisting',
            name='commercial_property_listing',
        ),
        migrations.RemoveField(
            model_name='roomlisting',
            name='sharehouse_listing',
        ),
        migrations.AddField(
            model_name='apartmentunitlisting',
            name='apartment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='properties.apartment'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='apartmentunitlisting',
            name='listing',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='listings.listing'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listing',
            name='is_listed_by_subscription',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='officelisting',
            name='commercial_property',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='properties.commercialproperty'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='officelisting',
            name='listing',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='listings.listing'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='othercommercialpropertyunitlisting',
            name='commercial_property',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='properties.commercialproperty'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='othercommercialpropertyunitlisting',
            name='listing',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='listings.listing'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='roomlisting',
            name='listing',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='listings.listing'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='roomlisting',
            name='sharehouse',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='properties.sharehouse'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='listing',
            name='featuring_payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='featured_listings', to='payments.payment'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='listing_payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='payments.payment'),
        ),
        migrations.DeleteModel(
            name='ApartmentListing',
        ),
        migrations.DeleteModel(
            name='CommercialPropertyListing',
        ),
        migrations.DeleteModel(
            name='SharehouseListing',
        ),
    ]
