# Generated by Django 4.2 on 2023-07-28 21:49

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_commercialproperty_unit_type'),
        ('listings', '0003_rename_rent_type_rentlisting_rent_term'),
    ]

    operations = [
        migrations.CreateModel(
            name='SharehouseListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listings.listing')),
                ('sharehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.sharehouse')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='RoomListing',
        ),
    ]
