# Generated by Django 4.2 on 2023-07-31 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0007_alter_payment_payment_purpose'),
        ('listings', '0004_sharehouselisting_delete_roomlisting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='featuring_payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='featured_listings', to='payments.payment'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='listing_payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='listings', to='payments.payment'),
        ),
    ]
