# Generated by Django 4.2 on 2023-08-04 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0006_alter_listing_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentlisting',
            name='rent_payment_period',
            field=models.CharField(choices=[('DAY', 'DAY'), ('WEEK', 'WEEK'), ('MONTH', 'MONTH'), ('YEAR', 'YEAR')], max_length=20),
        ),
    ]
