# Generated by Django 4.2 on 2023-08-05 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0007_alter_rentlisting_rent_payment_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='listing_payment_type',
            field=models.CharField(choices=[('SUBSCRIPTION', 'SUBSCRIPTION'), ('PAY_PER_LISTING', 'PAY_PER_LISTING')], max_length=30),
        ),
    ]
