# Generated by Django 4.2 on 2023-08-10 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0008_alter_listing_listing_payment_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='listing_type',
            field=models.CharField(choices=[('RENT', 'RENT'), ('SALE', 'SALE')], max_length=30),
        ),
    ]
