# Generated by Django 4.2 on 2023-08-12 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0010_alter_apartmentunitlisting_listing_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savedlisting',
            name='listing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listings.listing'),
        ),
    ]
