# Generated by Django 4.2 on 2023-07-31 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commons', '0002_tag_tagapplyto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
