# Generated by Django 4.2 on 2023-08-05 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commons', '0003_alter_tag_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='affixing_period_in_days',
        ),
        migrations.AddField(
            model_name='tag',
            name='apply_to',
            field=models.CharField(choices=[('LISTING', 'LISTING')], default='LISTING', max_length=50, verbose_name='tag name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tag',
            name='condition_code',
            field=models.CharField(default='', help_text='It can be if condition or anything else.', max_length=50),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='TagApplyTo',
        ),
    ]
