# Generated by Django 4.2 on 2023-08-05 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commons', '0004_remove_tag_affixing_period_in_days_tag_apply_to_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='condition_code',
            field=models.TextField(help_text='It can be if condition or anything else.'),
        ),
    ]
