# Generated by Django 4.2 on 2023-07-31 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0007_alter_payment_payment_purpose'),
        ('agents', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agentservicesubscription',
            name='subscription_currency',
        ),
        migrations.AddField(
            model_name='agentservicesubscription',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payments.payment'),
        ),
    ]
