# Generated by Django 4.2 on 2023-06-04 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0002_alter_agentbranch_options_alter_agent_referral_code_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='agentbranch',
            constraint=models.UniqueConstraint(fields=('agent', 'name'), name='unique_branch_name_per_agent_branch'),
        ),
        migrations.AddConstraint(
            model_name='agentbranch',
            constraint=models.UniqueConstraint(fields=('agent', 'is_main_branch'), name='only_single_mainbranch_per_agent'),
        ),
    ]
