# Generated by Django 4.2 on 2023-06-04 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0003_agentbranch_unique_branch_name_per_agent_branch_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='agentbranch',
            name='only_single_mainbranch_per_agent',
        ),
        migrations.AddConstraint(
            model_name='agentbranch',
            constraint=models.UniqueConstraint(condition=models.Q(('is_main_branch', True)), fields=('agent',), name='only_single_mainbranch_per_agent'),
        ),
    ]
