# Generated by Django 4.2 on 2023-07-31 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0003_remove_agentservicesubscription_subscription_currency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='agentbranch',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
