# Generated by Django 4.2 on 2023-06-04 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0004_remove_agentbranch_only_single_mainbranch_per_agent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentbranch',
            name='name',
            field=models.CharField(max_length=100, verbose_name='agent branch name'),
        ),
    ]
