# Generated by Django 4.2 on 2023-08-05 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0005_remove_agentservicesubscription_start_on_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentservicesubscription',
            name='subscription_price',
            field=models.DecimalField(decimal_places=2, help_text='It is the actual payable price after discounts are deducted. The original price is the price at ServiceSubscriptionPlan', max_digits=10),
        ),
    ]
