# Generated by Django 4.2 on 2023-06-05 00:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('agents', '0005_alter_agentbranch_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentadmin',
            name='user',
            field=models.OneToOneField(error_messages={'user_not_unique': 'A user can create only one agent or                                              must be assigned to a single agent as admin'}, help_text='The user that works as admin in the agent branch', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user admin'),
        ),
    ]
