# Generated by Django 4.2 on 2023-06-10 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0007_alter_agentadmin_agent_branch_alter_agentadmin_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agentreferraltracker',
            name='num_of_referrals_needed',
        ),
        migrations.AddField(
            model_name='agentreferraltracker',
            name='is_open',
            field=models.BooleanField(default=True, help_text='Does the agent have open/anawarded reward tracker?', verbose_name='is tracker open?'),
        ),
    ]
