# Generated by Django 4.2 on 2023-08-10 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0007_request_listing_alter_request_request_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestmessage',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='agents.request'),
        ),
    ]
