# Generated by Django 4.2 on 2023-06-10 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0008_remove_agentreferraltracker_num_of_referrals_needed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='referred_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='agents.agent', verbose_name='referrer'),
        ),
    ]
