# Generated by Django 4.2 on 2023-06-11 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0019_rename_reward_fixed_value_referralrewardplan_referee_reward_fixed_value_and_more'),
        ('agents', '0009_agent_referred_by'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AgentDiscount',
            new_name='AgentDiscountTracker',
        ),
    ]
