# Generated by Django 4.2 on 2023-07-13 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0010_rename_agentdiscount_agentdiscounttracker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='request_type',
            field=models.CharField(choices=[('VIEW_PROPERTY', 'View the property'), ('AVAILABILITY', 'Check availability'), ('INFORMATION', 'Get more information')], max_length=100, verbose_name='type of request'),
        ),
        migrations.AlterField(
            model_name='requestmessage',
            name='sender',
            field=models.CharField(choices=[('AGENT', 'Agent'), ('CLIENT', 'Client')], max_length=100, verbose_name='message sender'),
        ),
    ]
