# Generated by Django 4.2 on 2023-07-30 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_remove_agentnotificationpreference_notification_channel_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='agentnotificationchannelpreference',
            constraint=models.UniqueConstraint(fields=('agent', 'channel'), name='unique_agent_channel_preference_constraint'),
        ),
        migrations.AddConstraint(
            model_name='agentnotificationpreference',
            constraint=models.UniqueConstraint(fields=('agent', 'notification_topic'), name='unique_agent_preference_constraint'),
        ),
        migrations.AddConstraint(
            model_name='usernotificationchannelpreference',
            constraint=models.UniqueConstraint(fields=('user', 'channel'), name='unique_user_channel_preference_constraint'),
        ),
        migrations.AddConstraint(
            model_name='usernotificationpreference',
            constraint=models.UniqueConstraint(fields=('user', 'notification_topic'), name='unique_user_preference_constraint'),
        ),
    ]
