# Generated by Django 4.2 on 2023-07-30 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_agentnotificationchannelpreference_unique_agent_channel_preference_constraint_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentnotificationchannelpreference',
            name='channel',
            field=models.CharField(choices=[('EMAIL', 'Email'), ('IN_APP', 'In App'), ('SMS', 'SMS')], max_length=30),
        ),
        migrations.AlterField(
            model_name='usernotificationchannelpreference',
            name='channel',
            field=models.CharField(choices=[('EMAIL', 'Email'), ('IN_APP', 'In App'), ('SMS', 'SMS')], max_length=30),
        ),
    ]
