# Generated by Django 4.2 on 2023-07-31 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0003_remove_agentservicesubscription_subscription_currency_and_more'),
        ('notifications', '0004_alter_agentnotificationchannelpreference_channel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentnotification',
            name='agent_branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='agents.agentbranch'),
        ),
    ]
