# Generated by Django 4.2 on 2023-08-26 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0005_agentnotification_agent_branch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentnotificationchannelpreference',
            name='channel',
            field=models.CharField(choices=[('EMAIL', 'EMAIL'), ('IN_APP', 'IN_APP'), ('SMS', 'SMS')], max_length=30),
        ),
        migrations.AlterField(
            model_name='usernotificationchannelpreference',
            name='channel',
            field=models.CharField(choices=[('EMAIL', 'EMAIL'), ('IN_APP', 'IN_APP'), ('SMS', 'SMS')], max_length=30),
        ),
    ]
